-- Alter AuditAction enum to support auth and security auditing
ALTER TYPE "AuditAction" ADD VALUE 'USER_REGISTERED';
ALTER TYPE "AuditAction" ADD VALUE 'USER_LOGIN';
ALTER TYPE "AuditAction" ADD VALUE 'TOKEN_REFRESHED';
ALTER TYPE "AuditAction" ADD VALUE 'USER_LOGOUT';
ALTER TYPE "AuditAction" ADD VALUE 'PASSWORD_RESET_REQUESTED';
ALTER TYPE "AuditAction" ADD VALUE 'PASSWORD_RESET_COMPLETED';
